name: Build UI Tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 18
      - name: Accept Licences
        run: yes | ~/Library/Android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses
      - name: Run tests
        run: ./gradlew cleanManagedDevices --unused-only && ./gradlew pixel4api30DebugAndroidTest -Dorg.gradle.workers.max=1  -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect" -Pandroid.experimental.testOptions.managedDevices.emulator.showKernelLogging=true
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            '**/*/build/reports/androidTests/'
